# ========================================
# IMPORTANT: All configurations are fetched from Nacos, do not add configurations here
# Except for Nacos connection settings, all other configurations should be managed in Nacos Config Center
# ========================================

#spring.application.name=cloudflare-logs-producer
spring.config.import=optional:nacos:cloudflare-logs-producer.properties

spring.cloud.nacos.config.name=cloudflare-logs-producer.properties
spring.cloud.nacos.config.server-addr=${NACOS_HOST:10.10.72.40}:${NACOS_PORT:31590}
spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
spring.cloud.nacos.config.password=${NACOS_PASSWORD}
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:c2f15761-5874-47ac-bf66-9d9f793dd0cf}
spring.cloud.nacos.config.group=${NACOS_GROUP:DEFAULT_GROUP}
spring.cloud.nacos.config.shared-configs[0].data-id=${spring.cloud.nacos.config.name}
spring.cloud.nacos.config.shared-configs[0].group=${spring.cloud.nacos.config.group}
spring.cloud.nacos.config.shared-configs[0].refresh=true
spring.cloud.nacos.config.refresh-enabled=true
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.timeout=10000
spring.cloud.nacos.config.retry-times=3
spring.cloud.nacos.config.max-retry=3

# Nacos Discovery Configuration
spring.cloud.nacos.discovery.server-addr=${spring.cloud.nacos.config.server-addr}
spring.cloud.nacos.discovery.username=${spring.cloud.nacos.config.username}
spring.cloud.nacos.discovery.password=${spring.cloud.nacos.config.password}
spring.cloud.nacos.discovery.service=${spring.application.name}
spring.cloud.nacos.discovery.namespace=${spring.cloud.nacos.config.namespace}
spring.cloud.nacos.discovery.heart-beat-timeout=10000


# ??????
#spring.application.name=cloudflare-logs-producer
#server.port=8084
#
## ???????????????????
#logging.level.com.alibaba.cloud.nacos=INFO
#logging.level.org.springframework.web=INFO
#logging.level.org.springframework.http.converter=INFO
#logging.level.com.admin.bigdata=DEBUG
## Kafka producer/consumer ??????????? WARN
#logging.level.org.apache.kafka.clients.producer.KafkaProducer=ERROR
#logging.level.org.apache.kafka.clients.producer.internals.Sender=ERROR
#logging.level.org.apache.kafka.clients.producer.ProducerConfig=ERROR
#
#
## Actuator & Prometheus
#management.endpoints.web.exposure.include=health,info,prometheus
#management.endpoint.health.show-details=always
#management.metrics.tags.application=${spring.application.name}
#management.prometheus.metrics.export.enabled=true
#
## Kafka ????
#spring.kafka.bootstrap-servers=${KAFKA_SERVER:10.10.72.40:31050}
#
## Kafka Producer ????
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.acks=all
## ????????????????
#spring.kafka.producer.retries=10
## ??????? 10 ?
#spring.kafka.producer.enable-idempotence=true
## ??????????????
#
## ? ????
#spring.kafka.producer.linger-ms=50
## ???????????????????
#spring.kafka.producer.batch-size=1048576
## ??????? 1MB?????????
#spring.kafka.producer.buffer-memory=268435456
## 256MB ??????????
#
## ? ??????
#spring.kafka.producer.request-timeout-ms=120000
## ?????2??
#spring.kafka.producer.delivery.timeout-ms=180000
## ????????3??
#
## ? ????
##spring.kafka.producer.compression-type=snappy
## ?? snappy ?????????
#
## ????????????
#spring.kafka.producer.max-request-size=104857600
## ???????100MB
#
## topic ???
#cloudflare.allowed-projects=http_requests_u8_app,http_requests_gogame_app,http_requests_uu8_app,http_requests_credit_app,http_requests_kk_app