spring.application.name=domain

1|spring.config.import=optional:nacos:domain.properties
2|spring.cloud.nacos.config.name=domain.properties
3|spring.cloud.nacos.config.server-addr=${NACOS_HOST:nacos.middleware}:${NACOS_PORT:8848}
4|spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
5|spring.cloud.nacos.config.password=${NACOS_PASSWORD}
6|spring.cloud.nacos.config.file-extension=properties
7|spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:6c5b1db3-a808-4543-a87e-6642e372cb4f}
8|spring.cloud.nacos.config.group=${NACOS_GROUP:DEFAULT_GROUP}
9|spring.cloud.nacos.discovery.server-addr=${spring.cloud.nacos.config.server-addr}
10|spring.cloud.nacos.discovery.username=${spring.cloud.nacos.config.username}
11|spring.cloud.nacos.discovery.password=${spring.cloud.nacos.config.password}
12|spring.cloud.nacos.discovery.namespace=${spring.cloud.nacos.config.namespace}
13|
14|spring.application.name=domain
15|server.port=8091
16|spring.jackson.serialization.write-dates-as-timestamps=false
17|spring.jackson.deserialization.adjust-dates-to-context-time-zone=true
18|
19|spring.datasource.url=jdbc:mysql://${MYSQL_HOST:192.168.86.9}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:manage}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
20|spring.datasource.username=${MYSQL_USER:root}
21|spring.datasource.password=${MYSQL_PASSWORD}
22|spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
23|spring.datasource.hikari.maximum-pool-size=10
24|spring.datasource.hikari.minimum-idle=5
25|
26|spring.data.mongodb.host=${MONGODB_HOST:192.168.86.9}
27|spring.data.mongodb.port=${MONGODB_PORT:27017}
28|spring.data.mongodb.database=${MONGODB_DATABASE:domain}
29|spring.data.mongodb.username=${MONGODB_USERNAME:root}
30|spring.data.mongodb.password=${MONGODB_PASSWORD}
31|spring.data.mongodb.authentication-database=${MONGODB_AUTH_DB:admin}
32|
33|spring.data.redis.host=${REDIS_HOST:192.168.86.9}
34|spring.data.redis.port=${REDIS_PORT:6379}
35|spring.data.redis.password=${REDIS_PASSWORD}
36|spring.data.redis.database=${REDIS_DATABASE:0}
37|# XXL-Job Executor
38|xxl.job.admin.addresses=${XXL_JOB_ADMIN:http://192.168.86.9:8080/xxl-job-admin}
39|xxl.job.executor.appname=domain-service
40|xxl.job.executor.port=9997
41|xxl.job.accessToken=${XXL_JOB_TOKEN}
42|