# ========================================
# IMPORTANT: All configurations are fetched from Nacos, do not add configurations here
# Except for Nacos connection settings, all other configurations should be managed in Nacos Config Center
# ========================================

# Application Configuration
spring.config.import=optional:nacos:gateway.properties

# Nacos Configuration
spring.cloud.nacos.config.name=gateway.properties
spring.cloud.nacos.config.server-addr=${NACOS_HOST:192.168.86.9}:${NACOS_PORT:8848}
spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
spring.cloud.nacos.config.password=${NACOS_PASSWORD:nacos}
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:6c5b1db3-a808-4543-a87e-6642e372cb4f}
spring.cloud.nacos.config.group=${NACOS_GROUP:DEFAULT_GROUP}

spring.cloud.nacos.config.shared-configs[0].data-id=${spring.cloud.nacos.config.name}
spring.cloud.nacos.config.shared-configs[0].group=${spring.cloud.nacos.config.group}
spring.cloud.nacos.config.shared-configs[0].refresh=true

spring.cloud.nacos.config.refresh-enabled=true 
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.timeout=10000
spring.cloud.nacos.config.retry-times=3
spring.cloud.nacos.config.max-retry=3

# Nacos Discovery Configuration
spring.cloud.nacos.discovery.server-addr=${spring.cloud.nacos.config.server-addr}
spring.cloud.nacos.discovery.username=${spring.cloud.nacos.config.username}
spring.cloud.nacos.discovery.password=${spring.cloud.nacos.config.password}
spring.cloud.nacos.discovery.service=${spring.application.name}
spring.cloud.nacos.discovery.namespace=${spring.cloud.nacos.config.namespace}
spring.cloud.nacos.discovery.heart-beat-timeout=10000

# ??????
#spring.application.name=gateway
#
#server.port=8081
#logging.level.org.springframework.cloud.gateway=INFO
#logging.level.org.springframework.web=INFO
#logging.level.com.alibaba.cloud.nacos=INFO
#spring.main.web-application-type=reactive
#
## ???? AES-256 32
#secure.header.enabled=true
##secure.header.secret=u8m3xB7aVm92NdLtGjPQwf6eKzLY1tbW
#
## globalAuth ?????
#secure.header.global.secret=Qw7eJp9fLm2rTy4vGh6nZc8xKa1sDb3R
#
## bigDataAuth ?????
#secure.header.bigdata.secret=u8m3xB7aVm92NdLtGjPQwf6eKzLY1tbW
#
#
#management.endpoints.web.exposure.include=health,info,prometheus
#management.endpoint.health.show-details=always
#management.metrics.tags.application=${spring.application.name:gateway}
#management.prometheus.metrics.export.enabled=true
#management.server.port=8082
#
#spring.cloud.gateway.routes[0].id=gateway
#spring.cloud.gateway.routes[0].uri=lb://gateway
#spring.cloud.gateway.routes[0].predicates[0]=Path=/gateway/**
#spring.cloud.gateway.routes[0].filters[0]=RewritePath=/gateway/(?<segment>.*), /${segment}
#spring.cloud.gateway.routes[0].filters[1].name=GlobalAuth
#spring.cloud.gateway.routes[0].filters[1].args.enabled=true
#
#spring.cloud.gateway.routes[1].id=security
#spring.cloud.gateway.routes[1].uri=lb://security
#spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**
#spring.cloud.gateway.routes[1].filters[0]=RewritePath=/auth/(?<segment>.*), /${segment}
#spring.cloud.gateway.routes[1].filters[1].name=GlobalAuth
#spring.cloud.gateway.routes[1].filters[1].args.enabled=true
#
#spring.cloud.gateway.routes[2].id=manage
#spring.cloud.gateway.routes[2].uri=lb://manage
#spring.cloud.gateway.routes[2].predicates[0]=Path=/manage/**
#spring.cloud.gateway.routes[2].filters[0]=RewritePath=/manage/(?<segment>.*), /${segment}
#spring.cloud.gateway.routes[2].filters[1].name=GlobalAuth
#spring.cloud.gateway.routes[2].filters[1].args.enabled=true
#
#
#spring.cloud.gateway.routes[3].id=bigdata
#spring.cloud.gateway.routes[3].uri=lb://cloudflare-logs-producer
#spring.cloud.gateway.routes[3].predicates[0]=Path=/bigdata/**
#spring.cloud.gateway.routes[3].filters[0]=RewritePath=/bigdata/(?<segment>.*), /${segment}
#spring.cloud.gateway.routes[3].filters[1].name=BigDataAuth
#spring.cloud.gateway.routes[3].filters[1].args.enabled=true
#
## security
##spring.cloud.gateway.routes[1].id=security
##spring.cloud.gateway.routes[1].uri=lb://security
##spring.cloud.gateway.routes[1].predicates[0].name=Path
##spring.cloud.gateway.routes[1].predicates[0].args.pattern=/security/**
##spring.cloud.gateway.routes[1].filters[0].name=RewritePath
##spring.cloud.gateway.routes[1].filters[0].args.regexp=/security/(?<segment>.*)
##spring.cloud.gateway.routes[1].filters[0].args.replacement=/${segment}
##spring.cloud.gateway.routes[1].filters[1].name=globalAuth
##spring.cloud.gateway.routes[1].filters[1].args.enabled=true
#
## manage
##spring.cloud.gateway.routes[2].id=manage
##spring.cloud.gateway.routes[2].uri=lb://manage
##spring.cloud.gateway.routes[2].predicates[0].name=Path
##spring.cloud.gateway.routes[2].predicates[0].args.pattern=/manage/**
##spring.cloud.gateway.routes[2].filters[0].name=RewritePath
##spring.cloud.gateway.routes[2].filters[0].args.regexp=/manage/(?<segment>.*)
##spring.cloud.gateway.routes[2].filters[0].args.replacement=/${segment}
##spring.cloud.gateway.routes[2].filters[1].name=globalAuth
##spring.cloud.gateway.routes[2].filters[1].args.enabled=true
#
## bigdata
##spring.cloud.gateway.routes[3].id=bigdata
##spring.cloud.gateway.routes[3].uri=lb://cloudflare-logs-producer
##spring.cloud.gateway.routes[3].predicates[0].name=Path
##spring.cloud.gateway.routes[3].predicates[0].args.pattern=/bigdata/**
##spring.cloud.gateway.routes[3].filters[0].name=RewritePath
##spring.cloud.gateway.routes[3].filters[0].args.regexp=/bigdata/(?<segment>.*)
##spring.cloud.gateway.routes[3].filters[0].args.replacement=/${segment}
##spring.cloud.gateway.routes[3].filters[1].name=bigDataAuth
##spring.cloud.gateway.routes[3].filters[1].args.enabled=true
#
#
## https://logs-collector.sdjk35.com/bigdata/cloudflare_logs/http_requests_u8_app?header_X-Encrypted-Data=u8m3xB7aVm92NdLtGjPQwf6eKzLY1tbW
## https://logs-collector-test.sdjk35.com/bigdata/cloudflare_logs/http_requests_u8_app?header_X-Encrypted-Data=u8m3xB7aVm92NdLtGjPQwf6eKzLY1tbW
#
#spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
##spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=127.0.0.1,http://localhost:3000
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
#spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600













