# Application Name
spring.application.name=bot

# Nacos Configuration
spring.cloud.nacos.config.name=bot.properties
spring.cloud.nacos.config.server-addr=${NACOS_HOST:nacos.middleware}:${NACOS_PORT:8848}
spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
spring.cloud.nacos.config.password=${NACOS_PASSWORD}
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:public}
spring.cloud.nacos.config.group=${NACOS_GROUP:DEFAULT_GROUP}
spring.cloud.nacos.config.refresh-enabled=true
spring.cloud.nacos.config.enabled=true

spring.cloud.nacos.discovery.server-addr=${spring.cloud.nacos.config.server-addr}
spring.cloud.nacos.discovery.username=${spring.cloud.nacos.config.username}
spring.cloud.nacos.discovery.password=${spring.cloud.nacos.config.password}
spring.cloud.nacos.discovery.service=${spring.application.name}
spring.cloud.nacos.discovery.heart-beat-timeout=10000
spring.cloud.nacos.discovery.namespace=${spring.cloud.nacos.config.namespace}
