spring.application.name=bot

1|# ========================================
2|# IMPORTANT: All configurations are fetched from Nacos, do not add configurations here
3|# Except for Nacos connection settings, all other configurations should be managed in Nacos Config Center
4|# ========================================
5|
6|#spring.application.name=bot
7|spring.config.import=optional:nacos:bot.properties
8|
9|spring.cloud.nacos.config.name=bot.properties
10|spring.cloud.nacos.config.server-addr=${NACOS_HOST:nacos.middleware}:${NACOS_PORT:8848}
11|spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
12|spring.cloud.nacos.config.password=${NACOS_PASSWORD}
13|spring.cloud.nacos.config.file-extension=properties
14|spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:6c5b1db3-a808-4543-a87e-6642e372cb4f}
15|spring.cloud.nacos.config.group=${NACOS_GROUP:DEFAULT_GROUP}
16|
17|spring.cloud.nacos.config.shared-configs[0].data-id=${spring.cloud.nacos.config.name}
18|spring.cloud.nacos.config.shared-configs[0].group=${spring.cloud.nacos.config.group}
19|spring.cloud.nacos.config.shared-configs[0].refresh=true
20|spring.cloud.nacos.config.refresh-enabled=true
21|spring.cloud.nacos.config.enabled=true
22|spring.cloud.nacos.config.timeout=10000
23|spring.cloud.nacos.config.retry-times=3
24|spring.cloud.nacos.config.max-retry=3
25|
26|# Nacos Discovery Configuration
27|spring.cloud.nacos.discovery.server-addr=${spring.cloud.nacos.config.server-addr}
28|spring.cloud.nacos.discovery.username=${spring.cloud.nacos.config.username}
29|spring.cloud.nacos.discovery.password=${spring.cloud.nacos.config.password}
30|spring.cloud.nacos.discovery.service=${spring.application.name}
31|spring.cloud.nacos.discovery.namespace=${spring.cloud.nacos.config.namespace}
32|spring.cloud.nacos.discovery.heart-beat-timeout=10000
33|
34|