-- Cloudflare 账号表
CREATE TABLE IF NOT EXISTS account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT '账号名称',
    api_key VARCHAR(256) NOT NULL COMMENT 'Cloudflare API Token',
    description VARCHAR(500) DEFAULT NULL COMMENT '备注',
    tags VARCHAR(256) NOT NULL DEFAULT '' COMMENT '标签,逗号分隔(dns,zone,firewall,ssl,cache)',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '1=启用 0=禁用',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Cloudflare 账号';
