# ========================================
# IMPORTANT: All configurations are fetched from Nacos, do not add configurations here
# Except for Nacos connection settings, all other configurations should be managed in Nacos Config Center
# ========================================

#spring.application.name=telegram-bot-manager
spring.config.import=optional:nacos:telegram-bot-manager.properties

spring.cloud.nacos.config.name=telegram-bot-manager.properties
spring.cloud.nacos.config.server-addr=${NACOS_HOST:10.10.72.40}:${NACOS_PORT:31590}
spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
spring.cloud.nacos.config.password=${NACOS_PASSWORD:nacos}
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:c2f15761-5874-47ac-bf66-9d9f793dd0cf}
spring.cloud.nacos.config.group=${NACOS_GROUP:DEFAULT_GROUP}
spring.cloud.nacos.config.shared-configs[0].data-id=${spring.cloud.nacos.config.name}
spring.cloud.nacos.config.shared-configs[0].group=${spring.cloud.nacos.config.group}
spring.cloud.nacos.config.shared-configs[0].refresh=true
spring.cloud.nacos.config.refresh-enabled=true
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.timeout=10000
spring.cloud.nacos.config.retry-times=3
spring.cloud.nacos.config.max-retry=3

# Nacos Discovery Configuration
spring.cloud.nacos.discovery.server-addr=${spring.cloud.nacos.config.server-addr}
spring.cloud.nacos.discovery.username=${spring.cloud.nacos.config.username}
spring.cloud.nacos.discovery.password=${spring.cloud.nacos.config.password}
spring.cloud.nacos.discovery.service=${spring.application.name}
spring.cloud.nacos.discovery.namespace=${spring.cloud.nacos.config.namespace}
spring.cloud.nacos.discovery.heart-beat-timeout=10000

