# Application Name
spring.application.name=security

# Nacos Configuration
spring.cloud.nacos.config.name=security.properties
spring.cloud.nacos.config.server-addr=${NACOS_HOST:nacos.middleware}:${NACOS_PORT:8848}
spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
spring.cloud.nacos.config.password=${NACOS_PASSWORD}
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:public}
spring.cloud.nacos.config.group=${NACOS_GROUP:DEFAULT_GROUP}
spring.cloud.nacos.config.refresh-enabled=true
spring.cloud.nacos.config.enabled=true

# 禁用 discovery（用 service name 代替）
spring.cloud.nacos.discovery.enabled=false

jwt.expiration=86400

# RSA 密钥对（开发用）
jwt.rsa.private-key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLmtiI6LMDDvn4GfRqwakvCBTZXkQhaN3oGi6IagJAMTwd+Im0J/gcQl1AZGNRmKvdZzB0QNwjrNRmfq/Wt/6ttpFcYhy+qt5F7FhM+CK2DgsW4ro+DfCUMWOrXPX6LsEpR98O/dceO4UQl4OxDv8jJ3IsmDaXA+PBQ7N9xNohCwvxsA0UFKP4YmqmADp2/ycN1mJpSVIqmvQAYjv+urSCqL32APExuzi+UGqBUJrDerWpAnorxW95qyjFn8JkDvLKbzb/PGNE2fwQhCEM+rbnLMOKzyJCKp7vHAgBavLaqQSFQ0EEXbvxyas2VVdUNuuN3ZO/1MyL61ld/gdMl/hxAgMBAAECggEAc/QAOsQ/BV0fj/AMhM4BQRaH45b5ifsmaHvZWIxG6FNUYqY7GcVcNPqbQb5nFnEx5SNHkSDlE9+WS9Ysrx6Ft2X2EzBs5M3+riSBWF6bEWpGZazZ3xWNY+Mi9xB3vviREObjMFPYXE3Q2TTI8YxGscVQMMfpCvcQKNO0nAQ6HOF8Bo603CqE35VdJKmhEiu/CbFGzcFn8ZW6ruNmry0Q6m7+uIQGDqg9+JTeX3bvVmdU5YLE6tjBj7ddKTq7o3ObkiLeJ4x0NFSWqPGjzO9vN4De9K1MHg/0vz2mnc3JMKkglKmMEIMTZ5z1AZYmOw5S8A7Gz8lVN+vdQRPvswx0QQKBgQDzTC6TaRmvlu5wu6nOBVjv5Gd98lTnhrpFMIXMShMS2BNWQww0r21wrPR1NE8fPYP5iSwAOiF/EBy/3TmPd2zjeH8kABXiCOwQRznMBqDVf63Lm8X72tYPRrFud+G+TNmXYs+ZsMElpmPjJDq0jsq8gV30vDck4qAl9bNIwULiQQKBgQDV2r3B5vwaOxr5GXjEzO+Vy0AlMhfDeF5I3CGVZ6MCZ/fLLbECQIdMRUxAkiPfGncciQ8mKS37SWgCg3IaTLXhBLCbwRfRqTMXiNpdFoBfqPPz8PcwpRxAvOfRmvh/8jaPIBh32N9QGb6Fm3MsOmoCl5tDjBUaGAm5/GdDMOh07QKBgQCoMJXWD/wMDMmGX+pZ/tGmVhNJBep5fXKRf4TB6lTfiJhao9kUJ3KF+Uxh72OUZDhlCPq2eSHth7Db2QjkMKEgnqJs8FYI0KWDhHKvlE97spnFBf/H5SBVzJQt26jMvzwv5MLoud4arX7bysFnbQDczbtkFMVOUq8s8BnVyiRoQQKBgB52FnONIfDM/qjcekhTpdz2DbG0RF/6Q4G0sCg6NAu7qhmqQPFt7C9P065MLqqQq8l78U7KqMxVB25vGRngMNmou23kJ8IbjEjOpSFaHSW5Y97DQysyVjrhbVgcmZ2sqJDoNUtxJAC8/IMYFx/I5iBA2ldYqiQCCqxYFiV/HvclAoGAdJTtouWqSNJAyulGxotjKxxhkucIwwRRLOxK4PyFXPsHLT/OpCOVUBOc3xxEbyRUuiqF8XsFtYS/vJYXjh6PAEFF+KjPcMPnb7tLA9Li5Lb43idA4XlFNbFnNrCCNIDaPzc+GPFrOoePGUVYs0yv+moqO5bMvy0Fd2EuRGhVXxY=
jwt.rsa.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy5rYiOizAw75+Bn0asGpLwgU2V5EIWjd6BouiGoCQDE8HfiJtCf4HEJdQGRjUZir3WcwdEDcI6zUZn6v1rf+rbaRXGIcvqreRexYTPgitg4LFuK6Pg3wlDFjq1z1+i7BKUffDv3XHjuFEJeDsQ7/IydyLJg2lwPjwUOzfcaITAsL8bANFBSj+GJqpgA6dv8nDdZiaUlSKpr0AGI7/rq0gqi99gDxMbs4vlBqgVAaw3q1qQJ6K8VveasoxZ/CZA7yym82/zxjRNn8EIQhDPq25yzDis8iQiqe7xwIAWry2qkEhUNBBF278cmrNlVXVdLrjd2Tv9TMi+tZXf4HTJf4cQIDAQAB

feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000

logging.level.com.backend.security=INFO