# Cloudflare Service Config
# Nacos dataId: cloudflare.properties
# Group: DEFAULT_GROUP

## Service
service.name=cloudflare
service.port=8090
service.ip=127.0.0.1

## Cloudflare API
cf.base-url=https://api.cloudflare.com/client/v4

## MySQL
mysql.host=${MYSQL_HOST:192.168.86.9}
mysql.port=${MYSQL_PORT:3306}
mysql.user=${MYSQL_USER:root}
mysql.password=${MYSQL_PASSWORD:root123}
mysql.database=${MYSQL_DATABASE:cloudflare}

## Redis
redis.host=${REDIS_HOST:192.168.86.9}
redis.port=${REDIS_PORT:6379}
redis.password=${REDIS_PASSWORD:root123}
redis.database=${REDIS_DATABASE:0}

## MongoDB
mongodb.host=${MONGODB_HOST:192.168.86.9}
mongodb.port=${MONGODB_PORT:27017}
mongodb.user=${MONGODB_USERNAME:root}
mongodb.password=${MONGODB_PASSWORD:root123}
mongodb.database=${MONGODB_DATABASE:cloudflare}
mongodb.auth-db=admin
