# Cloudflare Service Config
# Nacos dataId: cloudflare.properties
# Group: DEFAULT_GROUP

## Service
service.name=cloudflare
service.port=8090
service.ip=127.0.0.1

## Cloudflare API
cf.base-url=https://api.cloudflare.com/client/v4

## MySQL
mysql.host=10.10.72.33
mysql.port=31130
mysql.user=root
mysql.password=
mysql.database=cloudflare

## Redis
redis.host=localhost
redis.port=6379
redis.password=
redis.database=0

## MongoDB
mongodb.host=10.10.72.40
mongodb.port=32290
mongodb.user=root
mongodb.password=root
mongodb.database=cloudflare
mongodb.auth-db=admin
